export type LegalPageSlug =
  | "privacy-policy"
  | "refund-policy"
  | "terms-and-conditions"
  | "shipping-policy"
  | "legal-information";

export const legalPages: Record<LegalPageSlug, { title: string; lines: string[] }> = {
  "privacy-policy": {
    "title": "Privacy Policy",
    "lines": [
      "# Privacy Policy",
      "**Last Updated: 26 July 2026**",
      "Welcome to **Think & Write Media & Publishing** (“Think & Write”, “we”, “us”, or “our”). We respect your privacy and are committed to protecting the personal information you share with us through our website, publishing services, programmes, consultations, and other interactions.",
      "This Privacy Policy explains how we collect, use, store, disclose, and protect your information when you visit **thinkandwrite.in**, submit an enquiry, purchase a publishing package, participate in one of our programmes, subscribe to our communications, or otherwise engage with our services.",
      "## 1. Information We May Collect",
      "Depending on your interaction with us, we may collect:",
      "* Full name",
      "* Email address",
      "* Mobile/WhatsApp number",
      "* Postal or billing address",
      "* Author biography and profile information",
      "* Manuscripts, book concepts, synopses, photographs, illustrations, and other publishing materials",
      "* Parent or guardian details for Young Author Programme participants",
      "* Billing, payment and transaction information",
      "* GST or invoicing information, where applicable",
      "* Communication and consultation records",
      "* Website usage information",
      "* IP address, browser type and device information",
      "* Information voluntarily provided through forms, email, WhatsApp, telephone, or consultations",
      "Payment information may be processed through third-party payment gateways or banking platforms. We may not directly store complete card, banking, UPI, or other sensitive payment credentials.",
      "## 2. How We Use Your Information",
      "Information collected by Think & Write may be used to:",
      "* Respond to enquiries and consultation requests",
      "* Provide publishing, editing, proofreading, ghostwriting, design, branding, marketing and related services",
      "* Process publishing package orders and payments",
      "* Communicate regarding manuscripts, designs, revisions, approvals and publishing progress",
      "* Create author profiles, book listings and publishing assets with author approval",
      "* Facilitate ISBN, Amazon or other publishing-platform processes where applicable",
      "* Deliver books and other physical materials",
      "* Issue invoices, receipts and transaction records",
      "* Administer the Young Author Programme",
      "* Provide customer support",
      "* Send service-related updates",
      "* Send newsletters, publishing information or promotional communication where permitted",
      "* Improve our website, programmes and services",
      "* Prevent fraud, misuse or security incidents",
      "* Comply with applicable legal and regulatory requirements",
      "## 3. Manuscripts and Intellectual Property",
      "Manuscripts, unpublished writings, book concepts and other creative material submitted to us are treated as confidential publishing materials and are used only for evaluating, developing or delivering the requested services.",
      "Submission of a manuscript does **not** transfer copyright ownership to Think & Write.",
      "Unless a separate written publishing, ghostwriting, licensing or assignment agreement specifically states otherwise, copyright in an author's original work remains with the author.",
      "## 4. Young Authors and Children's Information",
      "Our Young Author Programme is designed for young writers, including participants aged 8–18.",
      "Where legally required, participation by a minor must be initiated, approved or supervised by a parent or legal guardian.",
      "We may collect information about a young author only as reasonably necessary to provide publishing and related programme services.",
      "Parents or guardians may contact us regarding access, correction or deletion of a minor's personal information, subject to applicable legal and contractual requirements.",
      "## 5. Sharing of Information",
      "We do not sell or rent personal information.",
      "Information may be shared with trusted service providers where reasonably necessary for providing our services, including:",
      "* Editors and proofreaders",
      "* Designers and formatters",
      "* Printing and fulfilment partners",
      "* Courier/logistics providers",
      "* Payment processors",
      "* Website and technology service providers",
      "* Publishing and distribution platforms",
      "* Marketing or communication service providers",
      "Information may also be disclosed where required by law, court order, government authority or to protect our legitimate legal rights.",
      "## 6. Third-Party Platforms",
      "Our services may involve third-party platforms such as Amazon and other publishing, distribution, payment, social-media, courier or technology platforms.",
      "Use of those services may also be governed by their respective privacy policies and terms. Think & Write is not responsible for the independent privacy practices of third-party platforms.",
      "## 7. Cookies and Website Technologies",
      "Our website may use cookies and similar technologies to:",
      "* Maintain website functionality",
      "* Understand website traffic",
      "* Remember preferences",
      "* Improve website performance",
      "* Measure marketing effectiveness",
      "Users may manage cookies through their browser settings where available.",
      "## 8. Data Security",
      "We take reasonable administrative, organisational and technical measures to protect personal information from unauthorised access, disclosure, alteration, loss or misuse.",
      "However, no internet transmission or electronic storage system can be guaranteed to be completely secure.",
      "## 9. Data Retention",
      "We retain personal information only for as long as reasonably necessary to provide our services, maintain publishing and financial records, fulfil contractual obligations, resolve disputes, or comply with applicable laws.",
      "Certain publishing and transaction records may need to be retained for legal, accounting or business purposes.",
      "## 10. Your Choices and Rights",
      "Subject to applicable law, you may contact us to:",
      "* Request access to personal information held about you",
      "* Request correction of inaccurate information",
      "* Request deletion of information where legally permissible",
      "* Withdraw consent for optional marketing communications",
      "* Raise concerns regarding the handling of your personal information",
      "Withdrawal or deletion requests may not apply where information must be retained to fulfil an existing contract, publishing obligation or legal requirement.",
      "## 11. Marketing Communications",
      "Users may unsubscribe from promotional emails by using the unsubscribe option provided in such communication or by contacting us.",
      "Essential communications relating to active publishing projects, payments, contractual matters or service delivery may continue where necessary.",
      "## 12. Changes to This Privacy Policy",
      "Think & Write may update this Privacy Policy periodically to reflect changes in our services, technology, business practices or applicable laws.",
      "The revised policy will be published on this website with an updated “Last Updated” date.",
      "## 13. Contact Us",
      "For privacy-related questions, requests or grievances, please contact:",
      "**Think & Write Media & Publishing**",
      "Website: thinkandwrite.in",
      "Email: [publishing@thinkandwrite.in](mailto:publishing@thinkandwrite.in) / [thinkwritemediapublishing@gmail.com](mailto:thinkwritemediapublishing@gmail.com)",
      "India",
      "Additional registered-office and grievance-contact details may be added as applicable."
    ]
  },
  "refund-policy": {
    "title": "Refund & Cancellation Policy",
    "lines": [
      "# Refund & Cancellation Policy",
      "**Last Updated: 26 July 2026**",
      "At **Think & Write Media & Publishing**, our publishing, editorial, design, branding and author-development services involve customised professional work undertaken specifically for each author.",
      "This Refund & Cancellation Policy explains the circumstances under which cancellations and refunds may be considered.",
      "## 1. Publishing Packages and Service Bookings",
      "Payments made toward publishing packages, editing, proofreading, ghostwriting, book design, author branding, marketing, mentorship, consultation or other customised professional services are allocated toward project planning, professional resources and commencement of work.",
      "A client may request cancellation by contacting Think & Write in writing.",
      "## 2. Cancellation Before Work Begins",
      "If cancellation is requested **before any work has commenced**, Think & Write may approve a refund after deducting:",
      "* Payment gateway or transaction charges, where applicable;",
      "* Consultation or assessment charges already incurred;",
      "* Administrative or onboarding costs, where applicable.",
      "Any approved refund will be communicated in writing.",
      "## 3. Cancellation After Work Has Commenced",
      "Once work has commenced on a project, the amount attributable to work already performed, resources allocated, consultations completed or third-party expenses incurred will be non-refundable.",
      "Depending upon the stage of the project, Think & Write may determine whether any unused portion of the payment is eligible for refund.",
      "## 4. Non-Refundable Stages and Services",
      "Payments may become fully or substantially non-refundable once any of the following has occurred:",
      "* Manuscript review or editorial assessment has begun;",
      "* Editing or proofreading has commenced;",
      "* Ghostwriting work has commenced;",
      "* Cover concepts or designs have been prepared;",
      "* Interior formatting or typesetting has begun;",
      "* ISBN-related processing has been initiated or completed;",
      "* Publishing-platform setup has commenced;",
      "* Print-ready files have been prepared;",
      "* Printing has been ordered;",
      "* Author branding or marketing materials have been created;",
      "* Social-media, influencer or promotional campaigns have commenced;",
      "* Third-party services have been purchased on behalf of the client;",
      "* Final files have been approved by the author;",
      "* The book has been submitted for publication or distribution.",
      "## 5. Digital and Creative Deliverables",
      "Because editing, writing, design, formatting, branding and similar services involve customised intellectual and creative work, completed or substantially completed digital deliverables are generally non-refundable.",
      "Where a service includes revisions, reasonable revisions will be provided according to the scope of the selected package or written agreement.",
      "A request for revisions does not automatically create a right to a refund.",
      "## 6. Author Approval",
      "Authors are responsible for reviewing manuscripts, covers, interiors, metadata, author details and other materials provided for approval.",
      "Once an author provides final written approval for publication or printing, changes requested afterward may involve additional charges.",
      "Think & Write will not ordinarily provide refunds for errors that were visible in materials approved by the author before publication or printing.",
      "## 7. Printed Books",
      "Books printed specifically for an author or customer are produced based on approved files and quantities.",
      "Custom-printed books cannot ordinarily be returned or refunded merely because of a change of mind.",
      "If books received are materially damaged, defective, incorrectly printed or materially different from the approved specifications due to a production error, the customer should contact us within **7 days of delivery**, preferably with photographs and order details.",
      "After verification, Think & Write may arrange replacement, reprinting, credit or refund, as appropriate.",
      "## 8. Young Author Programme",
      "Fees paid for the Young Author Programme cover publishing, creative and programme resources reserved for the participant.",
      "Refund requests made before commencement may be considered subject to deductions for work already undertaken.",
      "Once editorial, design, publishing or programme services have commenced, refunds will be determined according to the work completed and costs already incurred.",
      "## 9. Third-Party Costs",
      "Payments made to third parties on behalf of an author—including printing, advertising, distribution, platform charges, courier charges or other external services—are non-refundable once committed or paid to the relevant third party, except where the third party itself provides a refund.",
      "## 10. Publishing Outcomes and Sales",
      "Payment for Think & Write services does not constitute a guarantee of:",
      "* Any particular number of book sales;",
      "* Bestseller status;",
      "* Media coverage;",
      "* Social-media followers or engagement;",
      "* Reviews or ratings;",
      "* Commercial success;",
      "* Acceptance by a particular retailer or distribution platform.",
      "Lack of a particular commercial result does not by itself qualify a project for a refund.",
      "## 11. Refund Processing",
      "Where a refund is approved, it will generally be processed through the original payment method or another mutually agreed method.",
      "Processing time may vary depending upon banks, payment gateways and other financial institutions.",
      "## 12. How to Request Cancellation or Refund",
      "Please send your request with the following information:",
      "* Author/client name",
      "* Project or book name",
      "* Package/service purchased",
      "* Payment details",
      "* Reason for cancellation/refund request",
      "Contact:",
      "**Think & Write Media & Publishing**",
      "Email: [publishing@thinkandwrite.in](mailto:publishing@thinkandwrite.in) / [thinkwritemediapublishing@gmail.com](mailto:thinkwritemediapublishing@gmail.com)",
      "Website: thinkandwrite.in",
      "All eligible refund requests will be assessed according to the project stage, services already delivered, costs incurred and applicable law."
    ]
  },
  "terms-and-conditions": {
    "title": "Terms & Conditions",
    "lines": [
      "# Terms & Conditions",
      "**Last Updated: 26 July 2026**",
      "Welcome to **Think & Write Media & Publishing**.",
      "These Terms & Conditions (“Terms”) govern your use of thinkandwrite.in and your purchase or use of publishing, editorial, writing, design, branding, marketing, mentorship and related services offered by Think & Write Media & Publishing (“Think & Write”, “we”, “us”, or “our”).",
      "By accessing our website, submitting an enquiry, purchasing a service or publishing package, making payment, or engaging Think & Write for a project, you acknowledge that you have read and accepted these Terms along with our Privacy Policy, Refund Policy and Shipping Policy.",
      "## 1. Our Services",
      "Think & Write may provide services including:",
      "* Book writing support",
      "* Ghostwriting",
      "* Manuscript review",
      "* Editing and proofreading",
      "* Book cover design",
      "* Interior formatting and typesetting",
      "* Publishing assistance",
      "* ISBN assistance",
      "* Amazon Kindle and paperback publishing assistance",
      "* Author profile development",
      "* Author branding",
      "* Personal branding",
      "* Graphic design",
      "* Book review services",
      "* Author mentorship",
      "* Social-media campaigns",
      "* Influencer marketing",
      "* Author visibility campaigns",
      "* Young Author Programme",
      "* Printing and distribution assistance",
      "* Other publishing and media-related services",
      "Specific deliverables depend upon the package or service purchased.",
      "## 2. Publishing Packages",
      "Features displayed under Launchpad, Author Pro, Legacy Author, Young Author Programme or other packages represent the services included at the time of purchase.",
      "Think & Write may revise package pricing, features or availability from time to time.",
      "Changes will not ordinarily reduce services already confirmed and paid for by an existing client unless mutually agreed.",
      "## 3. Payments",
      "Clients must pay fees according to the quotation, invoice, package or payment schedule agreed for their project.",
      "Work may commence only after receipt of the required advance or payment.",
      "Think & Write may pause work if scheduled payments remain outstanding.",
      "Taxes, payment gateway charges, printing, courier, advertising, distribution or third-party expenses may be charged separately where they are not expressly included in the selected package.",
      "## 4. Author Responsibilities",
      "The author/client is responsible for:",
      "* Providing accurate information;",
      "* Providing manuscripts and materials on time;",
      "* Ensuring that submitted material does not unlawfully infringe third-party rights;",
      "* Reviewing drafts and proofs;",
      "* Providing approvals within reasonable timelines;",
      "* Checking names, titles, spellings, photographs, acknowledgements, ISBN information and other book details;",
      "* Making payments according to the agreed schedule.",
      "Project timelines may be extended if required materials, feedback, approvals or payments are delayed.",
      "## 5. Copyright Ownership",
      "Unless otherwise agreed in a separate written agreement, the author retains copyright ownership of the author's original manuscript.",
      "Purchasing publishing services from Think & Write does not automatically transfer the author's copyright to Think & Write.",
      "Where Think & Write creates specific designs, layouts, marketing materials or other commissioned assets, usage and ownership rights may be determined by the applicable package or separate agreement.",
      "## 6. Author's Content Warranty",
      "By submitting content for publication, the author represents that they have the necessary rights or permissions to use that content.",
      "Authors must not knowingly submit:",
      "* Plagiarised material;",
      "* Unauthorised copyrighted material;",
      "* Defamatory or unlawful content;",
      "* Content that unlawfully violates privacy rights;",
      "* Images, illustrations or other assets for which required permissions have not been obtained.",
      "Think & Write reserves the right to refuse, suspend or discontinue a project involving potentially unlawful or infringing material.",
      "## 7. Editorial Changes",
      "Editing and proofreading improve a manuscript but do not guarantee that a publication will be completely free from every typographical, grammatical or factual error.",
      "The author remains responsible for reviewing and approving final proofs before publication.",
      "## 8. Cover and Design Approval",
      "Design concepts and revisions will be provided according to the selected package or agreed project scope.",
      "Additional concepts or revisions beyond the included scope may incur additional fees.",
      "Once the author gives final approval, subsequent changes may be chargeable.",
      "## 9. ISBN and Publishing Platforms",
      "Where ISBN assistance is included, Think & Write will assist according to applicable procedures and availability.",
      "ISBN allocation and platform approvals may involve government bodies, publishing platforms or other third parties outside Think & Write's direct control.",
      "Similarly, Amazon and other platforms maintain their own policies regarding listings, pricing, availability, reviews, distribution and account management.",
      "Think & Write cannot guarantee continued acceptance or availability of a title on any third-party platform.",
      "## 10. Royalties",
      "Royalty arrangements depend upon the publishing model, platform, format, printing cost, distribution channel and any separate publishing agreement applicable to the book.",
      "Where royalties are relevant, the specific royalty structure should be documented separately for the applicable project.",
      "## 11. Printing",
      "Printed colours, dimensions and finishes may vary slightly from digital previews because of differences in screens, printing processes, paper and finishing.",
      "Reasonable manufacturing variations do not constitute defects.",
      "The author is responsible for carefully reviewing and approving final print-ready files before bulk printing.",
      "## 12. Project Timelines",
      "Any publishing timeline provided is an estimate unless expressly agreed as a guaranteed deadline in writing.",
      "Timelines depend upon factors including:",
      "* Manuscript readiness",
      "* Editing requirements",
      "* Author response time",
      "* Revision rounds",
      "* Design approval",
      "* ISBN processing",
      "* Printing",
      "* Publishing-platform review",
      "* Distribution and courier timelines",
      "Think & Write will make reasonable efforts to meet communicated schedules but is not responsible for delays caused by circumstances outside its reasonable control.",
      "## 13. Marketing and Commercial Results",
      "Marketing, branding and visibility services are intended to improve author positioning and book visibility.",
      "Think & Write does not guarantee:",
      "* Book sales",
      "* Bestseller rankings",
      "* Reviews",
      "* Media coverage",
      "* Social-media growth",
      "* Followers",
      "* Engagement",
      "* Revenue",
      "* Awards",
      "* Commercial success",
      "Results depend upon numerous factors beyond our control.",
      "## 14. Young Author Programme",
      "Participation by minors must be undertaken with the knowledge and consent of a parent or legal guardian where required.",
      "Parents/guardians are responsible for reviewing and approving publication materials relating to participating minors.",
      "Think & Write may use a young author's name, photograph, book cover, achievement or success story for promotional purposes only where appropriate permission has been obtained.",
      "## 15. Confidentiality",
      "Think & Write will take reasonable steps to maintain the confidentiality of unpublished manuscripts and confidential client information.",
      "Confidential materials may be shared with team members, editors, designers, printers or other service providers only where reasonably necessary to complete the project.",
      "## 16. Refunds",
      "Refunds and cancellations are governed by our separate **Refund & Cancellation Policy**, which forms part of these Terms.",
      "## 17. Shipping",
      "Delivery of printed books and physical materials is governed by our **Shipping Policy**.",
      "## 18. Third-Party Services",
      "Think & Write may work with external service providers, including printers, couriers, payment gateways, publishing platforms, distribution platforms and technology providers.",
      "Think & Write is not responsible for independent policy changes, outages, suspensions or decisions made by such third parties, except to the extent responsibility cannot lawfully be excluded.",
      "## 19. Website Content",
      "Website text, branding, logos, graphics, layouts and other proprietary content belonging to Think & Write may not be copied, reproduced or commercially used without permission.",
      "## 20. Limitation of Liability",
      "To the extent permitted by applicable law, Think & Write will not be liable for indirect, incidental or consequential losses arising from use of its services, third-party platform actions, publishing delays or commercial performance of a book.",
      "Nothing in these Terms excludes rights or remedies that cannot legally be excluded under applicable Indian law.",
      "## 21. Force Majeure",
      "Think & Write will not be responsible for delays caused by circumstances reasonably beyond its control, including natural disasters, government restrictions, strikes, internet or technology failures, printing disruptions, courier interruptions or platform outages.",
      "## 22. Termination of Services",
      "Think & Write may suspend or terminate services where a client:",
      "* Fails to make agreed payments;",
      "* Repeatedly breaches agreed project terms;",
      "* Provides unlawful or infringing content;",
      "* Engages in abusive, threatening or fraudulent conduct;",
      "* Requests activity that would violate applicable law or third-party platform rules.",
      "Any outstanding charges for work already completed remain payable.",
      "## 23. Governing Law and Jurisdiction",
      "These Terms shall be governed by the laws of India.",
      "Subject to applicable consumer-protection laws and other mandatory jurisdictional requirements, disputes shall be subject to the jurisdiction of the competent courts in **Madhya Pradesh, India**, with the specific city/district to be stated according to Think & Write's registered office.",
      "## 24. Changes to These Terms",
      "Think & Write may update these Terms periodically. Updated Terms will be posted on the website along with the revised effective date.",
      "## 25. Contact",
      "For questions regarding these Terms:",
      "**Think & Write Media & Publishing**",
      "Website: thinkandwrite.in",
      "Email: [publishing@thinkandwrite.in](mailto:publishing@thinkandwrite.in) / [thinkwritemediapublishing@gmail.com](mailto:thinkwritemediapublishing@gmail.com)",
      "India"
    ]
  },
  "shipping-policy": {
    "title": "Shipping & Delivery Policy",
    "lines": [
      "# Shipping & Delivery Policy",
      "**Last Updated: 26 July 2026**",
      "This Shipping & Delivery Policy applies to printed books and other physical materials supplied by **Think & Write Media & Publishing**.",
      "Most of our publishing, editorial, design, branding and consultation services are delivered digitally and therefore do not require physical shipping.",
      "## 1. Digital Deliverables",
      "Digital services and files may be delivered through email, cloud storage, online platforms or other mutually agreed electronic methods.",
      "Digital deliverables may include:",
      "* Edited manuscripts",
      "* Proofreading files",
      "* Cover designs",
      "* Interior book files",
      "* Print-ready files",
      "* eBook files",
      "* Author branding assets",
      "* Marketing creatives",
      "* Other publishing materials",
      "Delivery timelines depend upon the scope of the project and author approval process.",
      "## 2. Printed Books",
      "Where printed author copies or book orders are included in a publishing package or purchased separately, books will be dispatched after:",
      "* Final manuscript approval;",
      "* Final cover approval;",
      "* Print-ready file approval;",
      "* Completion of applicable payments; and",
      "* Completion of printing.",
      "## 3. Processing and Printing Time",
      "Printing and dispatch times vary depending upon:",
      "* Book quantity",
      "* Binding",
      "* Page count",
      "* Paper specifications",
      "* Finishing requirements",
      "* Printer capacity",
      "* Delivery destination",
      "An estimated timeline will normally be communicated at the time of confirming the print order.",
      "Any timeline provided is an estimate unless expressly guaranteed in writing.",
      "## 4. Shipping Within India",
      "We may ship books and physical materials across serviceable locations in India through third-party courier or logistics partners.",
      "Delivery times depend upon the destination, courier availability and external logistics conditions.",
      "Remote or non-serviceable areas may require additional time or alternative delivery arrangements.",
      "## 5. International Shipping",
      "International shipping may be available on request.",
      "International orders may involve additional:",
      "* Shipping charges",
      "* Customs duties",
      "* Import taxes",
      "* Local handling charges",
      "Unless otherwise agreed, such charges are the responsibility of the recipient.",
      "## 6. Shipping Charges",
      "Shipping charges may:",
      "* Be included in a publishing package;",
      "* Be separately quoted; or",
      "* Depend upon quantity, weight and destination.",
      "Any applicable charges will be communicated before dispatch or included in the relevant quotation/invoice.",
      "## 7. Delivery Address",
      "Customers and authors are responsible for providing a complete and accurate delivery address, postal code and contact number.",
      "Think & Write will not be responsible for delays or failed delivery resulting from incorrect or incomplete information supplied by the recipient.",
      "Additional courier charges for re-shipment due to an incorrect address or unsuccessful delivery may be payable by the customer.",
      "## 8. Tracking",
      "Where tracking is available, tracking details may be shared with the recipient after dispatch.",
      "Tracking information is generated by the courier/logistics provider and may take time to become active.",
      "## 9. Delayed Shipments",
      "Delivery may occasionally be delayed because of:",
      "* Courier disruptions",
      "* Weather conditions",
      "* Public holidays",
      "* Natural disasters",
      "* Government restrictions",
      "* Strikes",
      "* Printing delays",
      "* Remote delivery locations",
      "* Other circumstances outside our reasonable control",
      "Think & Write will make reasonable efforts to assist customers in tracking delayed shipments.",
      "## 10. Damaged or Defective Books",
      "Customers should inspect books promptly after delivery.",
      "If books arrive materially damaged, defective or incorrectly printed, please contact us within **7 days of delivery** and provide:",
      "* Order/project details",
      "* Description of the issue",
      "* Clear photographs or video showing the damage/defect",
      "* Photograph of the shipping packaging where relevant",
      "After verification, Think & Write may arrange replacement, reprinting, credit or refund as appropriate.",
      "## 11. Lost Shipments",
      "If tracking indicates that a shipment may have been lost in transit, Think & Write will coordinate with the applicable courier partner.",
      "Replacement or other resolution will be determined after confirmation from the logistics provider.",
      "## 12. Author-Approved Printing",
      "Books printed after final author approval cannot ordinarily be returned because of:",
      "* Change of mind;",
      "* Content subsequently changed by the author;",
      "* Typographical errors already present in an approved proof;",
      "* Design elements previously approved by the author.",
      "Authors should therefore review all final proofs carefully before approving printing.",
      "## 13. Amazon and Third-Party Orders",
      "Books ordered directly through Amazon or another third-party retailer or distribution platform are subject to that platform's applicable shipping, delivery, return and refund policies.",
      "Think & Write does not directly control third-party fulfilment timelines.",
      "## 14. Contact",
      "For shipping or delivery assistance:",
      "**Think & Write Media & Publishing**",
      "Website: thinkandwrite.in",
      "Email: [publishing@thinkandwrite.in](mailto:publishing@thinkandwrite.in) / [thinkwritemediapublishing@gmail.com](mailto:thinkwritemediapublishing@gmail.com)",
      "India"
    ]
  },
  "legal-information": {
    "title": "Legal Information",
    "lines": [
      "# Legal Information",
      "**Last Updated: 26 July 2026**",
      "This website is operated by **Think & Write Media & Publishing**, a publishing, media and author-development organisation based in India.",
      "## Business Information",
      "**Business Name:** Think & Write Media & Publishing",
      "**Brand:** Think & Write",
      "**Website:** thinkandwrite.in",
      "**Email:** [publishing@thinkandwrite.in](mailto:publishing@thinkandwrite.in) / [thinkwritemediapublishing@gmail.com](mailto:thinkwritemediapublishing@gmail.com)",
      "**Country:** India",
      "**Registered Office:** [Insert Registered Business Address]",
      "**GSTIN:** [Insert GSTIN, if applicable]",
      "**Registration/CIN:** [Insert registration details, if applicable]",
      "## Nature of Business",
      "Think & Write provides professional services including publishing assistance, editing, proofreading, ghostwriting, book design, formatting, author branding, marketing support, mentorship, young-author programmes and related publishing and media services.",
      "## Intellectual Property",
      "Unless otherwise indicated, the Think & Write name, logo, website design, original website content, graphics and proprietary brand materials are owned by or licensed to Think & Write Media & Publishing.",
      "Unauthorised reproduction, distribution, modification or commercial use is prohibited.",
      "Authors retain rights in their original manuscripts and intellectual property except where otherwise agreed through a separate written contract.",
      "## Website Disclaimer",
      "Information provided on this website is intended to describe our publishing and related services.",
      "While reasonable efforts are made to keep information accurate and current, package features, prices, services and availability may change.",
      "Nothing on this website constitutes legal, financial or tax advice.",
      "## Third-Party Platforms",
      "References to Amazon, Kindle, social-media platforms, payment providers, distribution platforms or other third-party brands do not imply ownership, endorsement or partnership unless expressly stated.",
      "All third-party trademarks belong to their respective owners.",
      "## Grievance & Customer Support",
      "For service-related complaints, grievances or legal communication, please contact:",
      "**Grievance / Customer Support**",
      "Think & Write Media & Publishing",
      "Email: [publishing@thinkandwrite.in](mailto:publishing@thinkandwrite.in) / [thinkwritemediapublishing@gmail.com](mailto:thinkwritemediapublishing@gmail.com)",
      "**Grievance Officer:** [Insert Name]",
      "**Registered Address:** [Insert Registered Address]",
      "We will make reasonable efforts to acknowledge and address legitimate grievances in accordance with applicable law.",
      "## Governing Law",
      "Use of this website and our services is governed by applicable laws of India.",
      "Subject to applicable consumer-protection laws and mandatory jurisdictional requirements, disputes shall be subject to the jurisdiction of the competent courts corresponding to the registered office of Think & Write Media & Publishing.",
      "## Related Policies",
      "Users should also review our:",
      "* Privacy Policy",
      "* Refund & Cancellation Policy",
      "* Terms & Conditions",
      "* Shipping & Delivery Policy",
      "Together, these documents govern the use of our website and relevant services."
    ]
  }
};
